#nom du site
name: sur la route de l'indieweb...


#repository: https://github.com/christopheducamp/christopheducamp.github.io
description: selfdogfood sur jekyll
url: "http://christopheducamp.com"

#collections :essai en cours
collections:
  mes_notes:
    output: true

markdown: kramdown
highlighter : pygments
permalink: /:year/:month/:day/:title/

# Exclure ces fichiers du _site de production
exclude: [categories.html, Gemfile, Gemfile.lock, README.md, vendor, README.md, LICENSE]
gems:
  - jekyll-redirect-from
  - jemoji


    


