name: sur la route de l'indieweb...
markdown: redcarpet
highlighter : pygments
permalink: /:year/:month/:day/:title/
#repository: https://github.com/christopheducamp/christopheducamp.github.io
description: une route indieweb
#url: "http://christopheducamp.com"

ftp_host: ftp.christopheducamp.com
ftp_username: christoplj
ftp_dir: /www
ftp_passive: false


